### ISSUE TITLE
Cached files readable under NGiNX

### ISSUE THREAD

**Issue by philbraun** [websharks/zencache-kb#29]
Looking at the content of /wp-content/cache/zencache/cache/ I noticed a .htaccess file, which to me looks like it should disable access to the cached .html files from the outside (i.e. anything but WordPress).
However, my test server is NGiNX-only, and does not speak .htaccess, as far as I know.
I can easily open and read any and all cached html files directly, using any non logged-in browser. Is that the way it's supposed to be?

**Comment by jaswsinc** [comment]
> Is that the way it's supposed to be?

@philbraun No. These files should **not** be public. If you have user-specific caching disabled (default behavior), then there's nothing in these files that is super sensitive. However, I would agree that we should look at adding compatibility for Nginx also. I'm not sure if this is possible for ZenCache to do though.

@raamdev I'm guessing that we will need to display a notice if Nginx is detected. I think this is something that _must_ be done inside a server configuration file, since Nginx does not support `.htaccess`.

Referencing: http://kbeezie.com/protecting-folders-with-nginx/

---

_**Thought:** It might be worth it for us to name the `cache` directory `.cache`. I'm not sure if Nginx protects dot files automatically or not, but many hosting platforms will do this._

**Comment by raamdev** [comment]
@philbraun Thanks for the report!

NOTE: This repo is only for ZenCache KB Articles, not for reporting bugs. 

I've moved this bug report here: https://github.com/websharks/zencache/issues/435
